# Generated by Django 4.1.1 on 2022-09-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_creation", models.DateTimeField(auto_now_add=True)),
                ("date_of_last_modification", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("balance", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=30)),
                ("surname", models.CharField(max_length=30)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
