# Generated by Django 4.1.3 on 2022-11-06 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autoservice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dealer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_creation", models.DateTimeField(auto_now_add=True)),
                ("date_of_last_modification", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=30)),
                ("year_of_creation", models.IntegerField(default=0)),
                ("count_of_buyers", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DealerSaleHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_created=True)),
                ("cost", models.IntegerField(default=0)),
                ("count", models.IntegerField(default=0)),
                (
                    "autoservice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autoservice.autoservice",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autoservice.car",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dealer.dealer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DealerCarCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost", models.IntegerField(default=0)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autoservice.car",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dealer.dealer"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dealer",
            name="car_catalog",
            field=models.ManyToManyField(
                through="dealer.DealerCarCatalog", to="autoservice.car"
            ),
        ),
        migrations.AddField(
            model_name="dealer",
            name="sale_history",
            field=models.ManyToManyField(
                through="dealer.DealerSaleHistory", to="autoservice.autoservice"
            ),
        ),
    ]
