# Generated by Django 4.1.2 on 2022-10-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dealer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dealersalehistory",
            name="date_of_creation",
        ),
        migrations.RemoveField(
            model_name="dealersalehistory",
            name="date_of_last_modification",
        ),
        migrations.RemoveField(
            model_name="dealersalehistory",
            name="is_active",
        ),
    ]
