# Generated by Django 4.1.2 on 2022-10-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dealer", "0002_remove_dealersalehistory_date_of_creation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dealersalehistory",
            old_name="sold_car",
            new_name="car",
        ),
    ]
