# Generated by Django 4.1.3 on 2022-11-02 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autoservice", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="autoservicesalehistory",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="autoservicecarcatalog",
            name="autoservice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="autoservice.autoservice",
            ),
        ),
        migrations.AddField(
            model_name="autoservicecarcatalog",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="autoservice_car",
                to="autoservice.car",
            ),
        ),
        migrations.AddField(
            model_name="autoservice",
            name="car_catalog",
            field=models.ManyToManyField(
                through="autoservice.AutoserviceCarCatalog", to="autoservice.car"
            ),
        ),
        migrations.AddField(
            model_name="autoservice",
            name="sale_history",
            field=models.ManyToManyField(
                through="autoservice.AutoserviceSaleHistory",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
